### ISSUE TITLE
适用哪些编辑器？

### ISSUE THREAD

**Issue by crosswarm** [legendmohe/markdown_index#10]
或者说怎么安装使用呢？没什么概念哈，谢谢！

**Comment by aflyingtree** [comment]
vscode 搜索插件,安装,然后打开你要添加编号的md文件,ctrl+shift+p 然后在弹出的输入框输入markdown add index

**Comment by legendmohe** [comment]
> vscode 搜索插件,安装,然后打开你要添加编号的md文件,ctrl+shift+p 然后在弹出的输入框输入markdown add index

thx~
