### ISSUE TITLE
不能添加tab键

### ISSUE THREAD

**Issue by luobizheng** [legendmohe/markdown_index#12]
尝试了 \t  \\t  '\t'  都无效，建议增加tab键缩进 自动添加 标号 例如下面：

原文
中国
   陕西
      西安

转换
1.中国
   1.1.陕西
      1.1.1西安

**Comment by luobizheng** [comment]
补充：
原文
中国
陕西
西安
这块的缩进 没显示上 实际为：
原文
tab中国
tabtab陕西
tabtabtab西安

**Comment by legendmohe** [comment]
暂时不支持tab
