### ISSUE TITLE
'#' in code

### ISSUE THREAD

**Issue by FantDing** [legendmohe/markdown_index#2]
hello, I'm a Chinese user. I like this plugin.
But recently, I wrap python code in markdown and use the plugin to add index automaticlly. It went wrong that all python comments in markdown added index. Like this

![image](https://user-images.githubusercontent.com/21337200/32226330-4a6c6022-be83-11e7-9ac1-954093814401.png)

**Comment by meteor1113** [comment]
the same problem

**Comment by FantDing** [comment]
@meteor1113 I found a new plugin: `Markdown TOC`, and you can have a try

**Comment by legendmohe** [comment]
Please upgrade to version 0.0.4
