### ISSUE TITLE
能否忽略一级标题？

### ISSUE THREAD

**Issue by witskeeper** [legendmohe/markdown_index#4]
期望索引从二级标题开始，忽略一级标题

**Comment by legendmohe** [comment]
@witskeeper 暂时没有这个功能，请手动选取各个二级部分，分别运行markdownaddindex

**Comment by forwardNow** [comment]
![image](https://user-images.githubusercontent.com/9676409/39977128-4a566c2e-576a-11e8-9822-b7ad5cd60d3c.png)

在“#”前加个空格就能忽略一级标题

**Comment by xiaoxstz** [comment]
在“#”前加个空格，确实能忽略一级标题。虽然这样做并不会出问题，但是不太符合 Markdown 的语法；如果你使用了Markdown格式检查插件，你就会收到报警提示。

这个issue #25 提到了。可以选中一级标题之后的全部内容，然后运行命令 `Markdown add index` 即可。

因为该插件可以只根据选中内容来进行编号
