### ISSUE TITLE
正则有点问题

### ISSUE THREAD

**Issue by forwardNow** [legendmohe/markdown_index#6]
![image](https://user-images.githubusercontent.com/9676409/39977323-c42e9638-576b-11e8-85ca-3fb8f38ae437.png)
```
#1. a
#2. b
#3. c
...
#10. aa
#11. bb
```
第2次使用之后会变成
```
#1. a
#2. b
#3. c
...
#10. 1aa
#11. 1bb
```

**Comment by legendmohe** [comment]
Thanks! @forwardNow
