### ISSUE TITLE
How to remove index?

### ISSUE THREAD

**Issue by liangjiancang** [legendmohe/markdown_index#7]
怎么移除添加进来的索引？

**Comment by legendmohe** [comment]
暂时没有这个功能，请手动删除或者恢复历史记录

**Comment by AlexZhong22c** [comment]
> 暂时没有这个功能，请手动删除或者恢复历史记录

如果没有remove功能，这个的确有点坑啊。

我一个很久之前编好序号的一个文档，中间想插入一个2.2.2序号的。只能先remove，然后再生成一遍全局的序号，这种方案也是最容易理解的。

**Comment by legendmohe** [comment]
> > 暂时没有这个功能，请手动删除或者恢复历史记录
> 
> 如果没有remove功能，这个的确有点坑啊。
> 
> 我一个很久之前编好序号的一个文档，中间想插入一个2.2.2序号的。只能先remove，然后再生成一遍全局的序号，这种方案也是最容易理解的。

再运行时会重新生成的,包括你说的情况.他的意思是, 对于一个排好号的文档, 提供一个功能删掉里面的序号. 这个是没有的.

**Comment by Dunky-Z** [comment]
建议使用文档里说明无法移除，或者提示提前备份版本，不然大文档一次添加很多想移除就费劲了。
