### ISSUE TITLE
正文内的类似0.2.5的版本号出会被替换

### ISSUE THREAD

**Issue by fanzhi1977** [legendmohe/markdown_index#8]
如题，我文档内有描述我自己软件版本号的部分也会被替换。
如“从0.2.5升级到0.3"会替换成”从5升级到3"。

**Comment by legendmohe** [comment]
> 如题，我文档内有描述我自己软件版本号的部分也会被替换。
> 如“从0.2.5升级到0.3"会替换成”从5升级到3"。

已修正，请升级到0.0.9
