### ISSUE TITLE
配置为##后不起作用

### ISSUE THREAD

**Issue by tench** [legendmohe/markdown_index#9]
配置为##后怎么运行也不起作用了，只有设置回#时才有效果。

**Comment by yyalon** [comment]
setting `"markdownIndex.indexBase": "#"`,but run `Markdown add index` not work

**Comment by Brandonnogithub** [comment]
same problem

**Comment by mShining** [comment]
Same problem.
But "#" works.
Fine.

**Comment by legendmohe** [comment]
> 配置为##后怎么运行也不起作用了，只有设置回#时才有效果。
为什么要设置成“##”？能举个例子吗？

**Comment by legendmohe** [comment]
> 配置为##后怎么运行也不起作用了，只有设置回#时才有效果。

为什么要设置成“##”？能举个例子吗？

**Comment by tench** [comment]
我在# 里面放的是文档标题，整个文档就只有一个#标题，内容的标题一般从##开始，我现在都是在#的前面插一个空格来解决这个问题

**Comment by legendmohe** [comment]
> 我在# 里面放的是文档标题，整个文档就只有一个#标题，内容的标题一般从##开始，我现在都是在#的前面插一个空格来解决这个问题

```
# 这是标题

## 节1

内容内容内容

## 节2

内容内容内容
```

这样？indexBase是指用什么来表示标题，例如配成“=”，“@”， “*”等等。不是表示以什么来做首层的意思。你可以先选中你要编号的部分，运行命令，它只会处理你选中的部分。

**Comment by GSMix** [comment]
我是从仓库贡献者（@firejq）的一篇[博客](https://blog.csdn.net/jqsad/article/details/79255727)找过来的，博客说明的内容就是这个 issue 想要的功能。很奇怪，按道理他已经增加了这个功能了，为什么最新版本里不生效呢？ @legendmohe

**Comment by firejq** [comment]
> 我是从仓库贡献者（@firejq）的一篇[博客](https://blog.csdn.net/jqsad/article/details/79255727)找过来的，博客说明的内容就是这个 issue 想要的功能。很奇怪，按道理他已经增加了这个功能了，为什么最新版本里不生效呢？ @legendmohe

@GSMix 当时我确实提交了 [pr](https://github.com/legendmohe/markdown_index/pull/3)，但作者似乎没merge.

**Comment by chasezcz** [comment]
same problem
